# .github/workflows/build-frontend.yml

name: Build Frontend Docker Image Only # Workflow 的名称已更新，表示只编译

on:
  push:
    branches:
      - main # 当代码推送到 main 分支时触发此 workflow

jobs:
  build-only: # Job 名称已更新
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行器

    steps:
    - name: Checkout repository # 步骤1: 检出代码
      uses: actions/checkout@v4

    - name: Set up Docker Buildx # 步骤2: 设置 Docker Buildx，用于构建多平台镜像
      uses: docker/setup-buildx-action@v3

    # 移除了登录 Docker Hub 的步骤，因为不再需要推送

    - name: Build frontend image # 步骤3: 只编译前端镜像，不推送
      uses: docker/build-push-action@v5
      with:
        context: ./saleor-storefront # Dockerfile 的构建上下文，指向 saleor-storefront 目录
        file: ./saleor-storefront/Dockerfile # Dockerfile 的路径
        push: false # 设置为 false，表示只编译不推送
        # 移除了 tags，因为不推送就不需要标签
        build-args: | # 传递构建参数，NEXT_PUBLIC_SALEOR_API_URL 在 Dockerfile 中是 ARG
          NEXT_PUBLIC_SALEOR_API_URL=http://localhost:8000/graphql/ # 构建时使用的 API URL，这只是一个占位符，实际部署时会被覆盖

